export const Groups = [
  {
    name: 'ПИ-1-23',
    course: '1',
    direction: 'ПИ',
    numberOfStudents: 23,
    scolarshipStudents: 3,
    contractStudents: 20,
  },
  {
    name: 'ИБ-1-23',
    course: '1',
    direction: 'ПИ',
    numberOfStudents: 23,
    scolarshipStudents: 3,
    contractStudents: 20,
  },
  {
    name: 'ПИ-2-22',
    course: '2',
    direction: 'ПИ',
    numberOfStudents: 23,
    scolarshipStudents: 3,
    contractStudents: 20,
  },
  {
    name: 'ИБ-1-22',
    course: '2',
    direction: 'ИБ',
    numberOfStudents: 25,
    scolarshipStudents: 5,
    contractStudents: 20,
  },
  {
    name: 'ИБ-2-21',
    course: '3',
    direction: 'ИБ',
    numberOfStudents: 24,
    scolarshipStudents: 4,
    contractStudents: 20,
  },
  {
    name: 'ИБ-2-20',
    course: '4',
    direction: 'ИБ',
    numberOfStudents: 10,
    scolarshipStudents: 2,
    contractStudents: 8,
  },
  {
    name: 'ИБ-2-23',
    course: '1',
    direction: 'ИБ',
    numberOfStudents: 24,
    scolarshipStudents: 4,
    contractStudents: 20,
  },
];
